# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Pipeline Analysis Action

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file app/pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    - name: Veracode Pipeline-Scan
      # You may pin to the exact commit or the version.
      # uses: veracode/Veracode-pipeline-scan-action@e4326eb9e6735637c250e725c67d1b5f56d1a97c
      uses: veracode/Veracode-pipeline-scan-action@v1.0.15
      with:
        # vid
        vid: ${{secrets.veracode_api_id }}
        # vkey
        vkey: ${{secrets.veracode_api_key }}
        # Filename of the packaged application to upload and scan.
        file: app/target/verademo.war
        # GITHUB_TOKEN or a repo scoped PAT.
        token: # default is ${{ github.token }}
        # Name of the Veracode default policy or custom-built policy to apply to the scan results.
        veracode_policy_name: # optional
        # DPERECATED, WILL BE REMOVED WITH NEXT VERSION - Name of the security policy to download as a file. Required only if you want to download the configuration for a custom policy defined by your organization. After downloading the policy, you can provide this file in a subsequent command using the policy_file parameter.
        request_policy: # optional
        # Fail the pipeline job if the scan finds flaws of the specified severities. Enter a comma-separated list of severities in quotation marks.
        fail_on_severity: # optional
        # Fail the pipeline job if the scan finds flaws of the specified CWEs. Enter a comma-separated list of CWE IDs.
        fail_on_cwe: # optional
        # Filter the flaws that exist in the specified baseline file and show only the additional flaws in the current scan.
        baseline_file: # optional
        # DPERECATED, WILL BE REMOVED WITH NEXT VERSION - Name of the Veracode default policy rule to apply to the scan results. You can only use this parameter with a Veracode default policy.
        policy_name: # optional
        # Name of the local policy file you want to apply to the scan results.
        policy_file: # optional
        # Amount of time, in minutes, for the Pipeline Scan to wait before reporting an unsuccessful scan if the scan does not complete. Default is 60 minutes, which is also the maximum value.
        timeout: # optional
        # Enter true to show detailed messages for each issue in the results summary.
        issue_details: # optional
        # Enter true to show a human-readable results summary on the console. Default is true.
        summary_display: # optional
        # Enter true to show the JSON containing the scan results on the console. Default is false.
        json_display: # optional
        # Enter true to display detailed messages in the scan results. Default is false.
        verbose: # optional
        # Enter true to save the scan results as a human-readable file. Default is false.
        summary_output: # optional
        # Enter the filename of the scan results summary file. The file is stored in the current directory. Default is results.txt.
        summary_output_file: # optional
        # Enter true to save the scan results in JSON format. Default is true.
        json_output: # optional
        # Rename the JSON file that contains the scan results. The file is stored in the current directory. Default filename is results.json.
        json_output_file: # optional
        # Enter the filename in the current directory to save results that violate pass-fail criteria. Default is filtered_results.json.
        filtered_json_output_file: # optional
        # Enter the name of the CI/CD code repository that runs a Pipeline Scan. This parameter adds the repository name to the scan results, which can help you track scans across repositories.
        project_name: # optional
        # Enter the source control URL for the CI/CD code repository that runs a Pipeline Scan.
        project_url: # optional
        # Enter the source control reference, revision, or branch for the CI/CD code repository that runs a Pipeline Scan.
        project_ref: # optional
        # Enter the [application profile](https://docs.veracode.com/r/request_profile) ID for the application you want to upload and scan.
        app_id: # optional
        # Enter one these values, which are case-sensitive, for the type of development stage: Development, Testing, Release.
        development_stage: # optional
        # Enable debug mode. 1 for on
        debug: # optional
        # Enable the storage of a baseline file. Takes true or false
        store_baseline_file: # optional
        # Enter the branch name where the baseline file should be stored
        store_baseline_file_branch: # optional
        # From which results should the baseline file be created. standard = full results || filtered = filtered results
        create_baseline_from: # optional
        # Fail the build upon findings. Takes true or false
        fail_build: # optional
        # Enter a case-sensitive, comma-separated list of name patterns that represent the names of the modules to scan as top-level modules. Veracode identifies these modules during prescan. The * wildcard matches zero or more characters. The ? wildcard matches exactly one character. For example, to include various module names that contain module: --include "module 1, module-*, module2.jar". The scan results show the names of the modules that Veracode identified and the modules included in the scan. This parameter does not pause, stop, or impact the performance of your pipeline.
        include: # optional
        # Enable it, if artifact version 2 requires usage
        use_upgraded_version: # optional

   - name: SCA Agent
      env: 
        SRCCLR_API_TOKEN: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTM4ODExLCJleHAiOjE3NDI5OTg4MzQsImF1dGhvcml0aWVzIjoiQUdFTlQiLCJqdGkiOiI3ZTk1YmNjOC1lNWZhLTQ4MGQtODhkMy0wMGZjOTk2Nzc5NzQiLCJjbGllbnRfaWQiOiIiLCJzY29wZSI6W119.sB7tdwy728gnKlTZVWOviCQ5ix0AJfTo3qI229jVhsqKOe_IkYqUfFJo0xcAERQ1NXLjGl_u-QwuD576A0kNXOdNrMhpBntckaoAs4P7iwgnCkwUplz8KOeg3Q-Z2HxH0ps-ziAKb5mzXxlj3TYDHcxEe5U2ngLDs1WOa2Lolso
      run: curl -sSL https://sca-downloads.veracode.com/ci.sh | sh srcclr scan --url https://github.com/veracode/example-ruby
