on:
  workflow_dispatch:

jobs:
  promote_sandbox:
    name: Promote Sandbox
    runs-on: ubuntu-22.04
  
    steps:
    - name: Veracode Profile Sandboxes Helper
      # You may pin to the exact commit or the version.
      # uses: veracode/veracode-sandboxes-helper@baa0a8458605b92d261b6b8f7801fa67fdce501b
      uses: veracode/veracode-sandboxes-helper@v1.0.0
      with:
        # The activity expected from the Action: clean, promote-latest-scan, remove-sandbox
        activity: promote-latest-scan # optional
        # Veracode Application name
        app-name: verademo-github-integration
        # Sandbox name for actions related to a specific Sandbox
        sandbox-name: 'Release Candidate' # optional
        # The amount of oldest scanned-in sandboxes to remove
        # clean-amount: # optional, default is 1
        # Deletes the sandbox after its promotion. Only works with the [promote] activity. Default is false
        # delete-on-promote: # optional, default is false
        # The number of days which the sandbox had no activity
        # clean-modified-before: # optional, default is 0
            
